<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdn" nsURI="mdn" nsPrefix="">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sdn">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//NetworkNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//Policy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyObjects" upperBound="-1"
        eType="#//PolicyObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.ControllerFigure"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/controller.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PacketHeaders">
    <eLiterals name="IN_PORT"/>
    <eLiterals name="MAC_SRC" value="1"/>
    <eLiterals name="MAC_DST" value="2"/>
    <eLiterals name="VLAN_ID" value="3"/>
    <eLiterals name="VLAN_PRIO" value="4"/>
    <eLiterals name="ETH_TYPE" value="5"/>
    <eLiterals name="IP_SRC" value="6"/>
    <eLiterals name="IP_DST" value="7"/>
    <eLiterals name="IP_TOS" value="8"/>
    <eLiterals name="IP_PORT" value="9"/>
    <eLiterals name="L4_SPORT" value="10"/>
    <eLiterals name="L4_DPORT" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/host.gif"/>
      <details key="figure" value="figures.HostFigure"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostSwitch" eType="#//Switch">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//NetworkNode">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/switch.gif"/>
      <details key="figure" value="figures.SwitchFigure"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switchController" upperBound="-1"
        eType="#//Controller">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switches" upperBound="-1"
        eType="#//Switch">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
        <details key="switches.constraint" value="self &lt;> oppositeEnd"/>
        <details key="source.constraint" value="self &lt;> oppositeEnd"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Actions">
    <eLiterals name="FORWARD"/>
    <eLiterals name="DROP" value="1"/>
    <eLiterals name="MODIFY" value="2"/>
    <eLiterals name="MONITOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.PolicyFigure"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/policy.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceHostPolicy" upperBound="-1"
        eType="#//Host" transient="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
        <details key="tool.name" value="sourceHost"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetHostPolicy" upperBound="-1"
        eType="#//Host" transient="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
        <details key="tool.name" value="targetHost"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyCondition" eType="#//Condition"
        transient="true">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyAction" eType="#//Action">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//PolicyObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.ActionFigure"/>
      <details key="label" value="type"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/action.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Actions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionPacketHeader" eType="#//PacketHeader">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionForwardToNode" eType="#//NetworkNode">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//PolicyObject">
    <eAnnotations source="gmf.node">
      <details key="label" value="condition"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/condition.gif"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="figures.ConditionFigure"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="#//Conditions"
        defaultValueLiteral="WHERE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionTime" eType="#//Time">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionTraffic" eType="#//Traffic">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionPacket" eType="#//PacketHeader">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="none"/>
        <details key="source.decoration" value="none"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Conditions">
    <eLiterals name="WHEN"/>
    <eLiterals name="WHERE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationalOperators">
    <eLiterals name="EQUAL_TO"/>
    <eLiterals name="NOT_EQUAL_TO" value="1"/>
    <eLiterals name="GREATER_THAN" value="2"/>
    <eLiterals name="LESS_THAN" value="3"/>
    <eLiterals name="IN"/>
    <eLiterals name="OUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Traffic" eSuperTypes="#//PolicyObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.TrafficFigure"/>
      <details key="label" value="operator,value,unit"/>
      <details key="label.pattern" value="{0}: {2}{1}"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/traffic.gif"/>
      <details key="label.placement" value="external"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelationalOperators"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="MB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time" eSuperTypes="#//PolicyObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.TimeFigure"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/time.gif"/>
      <details key="label.placement" value="external"/>
      <details key="label" value="operator,beginDate,endDate"/>
      <details key="label.pattern" value="{0}: {1} - {2}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelationalOperators"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beginDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacketHeader" eSuperTypes="#//PolicyObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="figures.PacketHeaderFigure"/>
      <details key="label.icon" value="false"/>
      <details key="tool.small.bundle" value="mdn.edit"/>
      <details key="tool.small.path" value="/icons/full/obj16/packetheader.gif"/>
      <details key="label.placement" value="external"/>
      <details key="label" value="operator,header,value"/>
      <details key="label.pattern" value="{0}: [{1}] {2}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//RelationalOperators"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="#//PacketHeaders"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyObject" abstract="true"/>
</ecore:EPackage>
